### ISSUE TITLE
Multi-issues in game ?

### ISSUE THREAD

**Issue by AzurikPerathia** [BryanHaley/sm64hlmov#5]
I've tested your mod a little, but there's a certain problem that's preventing it from progressing! At least I've configured my keys so that this doesn't happen!

The first and owl that we can not take what is annoying! 

https://github.com/user-attachments/assets/e2a79a72-431b-4cfe-9777-2b9d84dc5527

The second is that the place we're aiming the cannon at doesn't reflect reality! In fact, when I aim the cannon, it shoots much too much! 

https://github.com/user-attachments/assets/e694b968-3b9b-407c-9aea-c12c5cab45df

Another problem is the need for an add-on for double jumps or jumps a little higher than the others, as some places remain almost inaccessible. 

Otherwise I love your mod! I'm thinking of making a YouTube video when everything's stable (I'm thinking of doing a let's play on it).

**Comment by BryanHaley** [comment]
Hi, the mod is in fact fully playable.

https://youtu.be/qOUOsLOyilk?si=IYRdqPfLIav6vugr

This repository is specifically for the Speedrun associated with this modpack. I suggest you make these comments to the author of mQuake for the mQuake project specifically; that is the base movement mod which is also aimed at casual play. This modpack specifically will not be making changes for the purpose of casual play.

**Comment by Tom-J991** [comment]
Hey @BryanHaley, not sure if it really is exactly fully playable, at least for a 120 star run.
Been running into a specifically annoying bug in Tall Tall Mountain where after collecting 100 coins the player seems to freeze completely, I'd think this could be occuring due to the pause during the star spawn not unpausing for whatever reason. It's not a major issue since I can still exit the level through the pause menu.
It's definitely very strange to me that it seems to be occuring only in that level and only for that star. (Possibly could be effecting other levels? need to play further in to know.)
But what is stranger is that this bug doesn't seem to occur if I collect the 100 coins in the slide area,  the issue there is there's no surfaces that'll allow me to jump and collect the star at least from what I can find. Maybe something else in the mountain area is causing issues?

I can upload a clip if necesssary, not exactly sure what the game itself provides me to get more information about the bug.
